apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: mlops-lab
  labels:
    app: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080