apiVersion: v1
kind: Service
metadata:
  name: ml-inference-service
  namespace: mlops-lab
  labels:
    app: ml-inference
spec:
  type: ClusterIP
  selector:
    app: ml-inference
  ports:
  - name: http
    port: 5000
    targetPort: 5000